# {+}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-{+}
#                                                                  
#                            WeatherLockX v1.0                        
#                                                                  
#                             Author: Skillux                         
#                                                                  
# {+}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-{+}


# {+}=--=-=-=-=-=-=-=-=-=-=-=[ Placeholders ]=-=-=-=-=-=-=-=-=-=-=-=-={+}

# %weather% : Represents the WeatherLock mode that is being set (Sunny/Rainy/Thundering).


# {+}-=-=-=-=-=-=-=-=-=-=-=-=-=[ Messages ]=-=-=-=-=-=-=-=-=-=-=-=-=-={+}

# Customize the message that appears when you reload the config (/weatherlock reload):
Reload-Message: '&8[&3WeatherLockX&8] &aThe config file has been reloaded!'


# Customize the message that appears when a player runs the command (/weatherlock) without permission:
No-Permission: '&8[&3WeatherLockX&8] &4You do not have permission to use this command!'


# Customize the message that appears when a WeatherLock mode is already selected:
Already-Enabled: '&8[&3WeatherLockX&8] &cThis WeatherLock mode is already enabled in this world!'


# Customize the message that appears when WeatherLock is toggled off in the player's current world"
Turned-Off: '&8[&3WeatherLockX&8] &7WeatherLock has been toggled &coff&7. The weather cycle is back to normal.'


# Customize the message that appears when a WeatherLock mode is selected in a player's current world:
WeatherLock-Set: '&8[&3WeatherLockX&8] &7Successfully locked the weather to &3%weather%&7 in your current world. Use the command &b/weatherlock off &7to return the normal weather cycle.'


# Customize the message that appears when the command is used incorrectly:
Invalid-Usage: '&8[&3WeatherLockX&8] &cInvalid Usage. Use the command &3/weatherlock &cfor help.'


# Customize the message that appears when a player attempts to toggle off WeatherLock without having any mode selected.
No-Selected-Mode: '&8[&3WeatherLockX&8] &cYou do not have any WeatherLock modes selected to turn off. Use the command &3/weatherlock &cfor help.'



# {+}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-{+}
#                                                                  
#                              Any Questions?                         
#                                                                  
#                      Message me on Spigot: @Skillux                 
#                                                                  
# {+}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-{+}
