name: WeatherLockX
main: me.skillux.weatherlockx.Main
author: Skillux
version: 1.0
commands:
  weatherlock:
    usage: /<command> [sun|rain|thunder|reload|off]
    description: Changes and locks the weather to the either sunny, rainy, or thundering.
    aliases: [wl, lockweather, weatherlockx, wlx, lw]